server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
     
        
    discovery:
      enabled: true

